name: Generate Snake Animation

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: Platane/snk@v3
        with:
          github_user_name: JumpCodeFrog
          outputs: |
            dist/github-contribution-grid-snake.svg?color_snake=%23FFB000&color_dots=%230F0B06,%238C5E22,%23C07E1E,%23E8A33D,%23FFB000
            dist/github-contribution-grid-snake-dark.svg?color_snake=%23FFB000&color_dots=%230F0B06,%238C5E22,%23C07E1E,%23E8A33D,%23FFB000

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: output
          publish_dir: dist
